---
apiVersion: apps/v1	
kind: Deployment	
metadata:	
  name: petclinic-api-deployment	
  namespace: dev	
spec:	
  replicas: 1	
  selector:	
    matchLabels:	
      app: petclinic-api	
  template:	
    metadata:	
      labels:	
        app: petclinic-api	
    spec:	
      containers:	
      - name: petclinic-api	
        image: tntaksreg.azurecr.io/petclinic-api:latest	
        ports:	
        - containerPort: 9966	

---
apiVersion: v1	
kind: Service	
metadata:	
  name: petclinic-api-service	
  namespace: dev	
spec:	
  type: ClusterIP	
  selector:	
    app: petclinic-api	
  ports:	
    - protocol: TCP	
      port: 80	
      targetPort: 9966	

---
apiVersion: networking.k8s.io/v1beta1	
kind: Ingress	
metadata:	
  name: petclinic-api-ingress	
  namespace: dev	
  annotations:	
    kubernetes.io/ingress.class: addon-http-application-routing	
spec:	
  rules:	
  - host: api.e46708b92c054086909b.eastus.aksapp.io	
    http:	
      paths:	
      - backend:	
          serviceName: petclinic-api-service	
          servicePort: 9966
        path: /
