apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-rest
  labels:
    app: petclinic-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-rest
  template:
    metadata:
      labels:
        app: petclinic-rest
    spec:
      containers:
      - name: petclinic-rest
        image: tntaksreg.azurecr.io/:rest
        ports:
        - containerPort: 9966
        
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-rest-service
spec:
  type: ClusterIP
  selector:
    app: ui
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9966
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: petclinic-rest-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: petclinic-rest.e46708b92c054086909b.eastus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: petclinic-rest-service
          servicePort: 80
        path: /
